### ISSUE TITLE
add Chile to list of countries

### ISSUE THREAD

**Issue by PixlTracer** [acdh-oeaw/dhcr-main#114]
there is an account request form Santiago de Chile, Chile
-- I could not approve the user because Chile is missing in the list of countries.
please add the country to the list @patrickakk, thank you.

**Comment by patrickakk** [comment]
@PixlTracer Since version 2024-05, released on 2024-05-30, it's possible for you, as administrator, to manage the list of countries yourself. Please check the screenshot for more details.

Can you change the label to Done if this solves your problem?

![image](https://github.com/user-attachments/assets/504d2fde-59ba-404a-9788-5a9ed941c903)

**Comment by PixlTracer** [comment]
thanks!
