### ISSUE TITLE
Sorting of lists in login area does not work properly

### ISSUE THREAD

**Issue by PixlTracer** [acdh-oeaw/dhcr-main#116]
In the dashboard --> Category lists --> cities and institutions, the sorting ascending / descending (a-z / z-a) does not work anymore, can you fix this @patrickakk?
thanks!

**Comment by patrickakk** [comment]
@PixlTracer 

Where did this error occur? Was that in production?

**Comment by PixlTracer** [comment]
yes! @patrickakk just now, in production at "cities" and "institutions"
https://dhcr.clarin-dariah.eu/cities
https://dhcr.clarin-dariah.eu/institutions
neither sorting by `ID` nor `Name` works.

**Comment by patrickakk** [comment]
@PixlTracer  Thanks for the bug report.

This seems to apply to all "lists" in the login area, that (a part) of the sorting doesn't work. 

I've also found a possible solution.

**Comment by patrickakk** [comment]
@PixlTracer 
cc @IvdL22 

A fix has been implemented. Could you test it @PixlTracer, since you've reported the bug?

Is seems it affected the sorting of most of the lists in the login area. Two lists are only accessible by moderators, and don't appear in your dashboard if you are "only" administrator. I've specified that in brackets. And also tested them.

As well, as a bonus ;) the option has been added to sort on two additional columns. This is also specified in  brackets.

Here are the URL's:
https://test-dhcr.clarin-dariah.eu/users/approve (added: also sort by request date)
https://test-dhcr.clarin-dariah.eu/courses/approve
https://test-dhcr.clarin-dariah.eu/courses/expired

https://test-dhcr.clarin-dariah.eu/courses/my-courses
https://test-dhcr.clarin-dariah.eu/courses/all
https://test-dhcr.clarin-dariah.eu/courses/moderated (only mods)

https://test-dhcr.clarin-dariah.eu/users/pending-invitations (added: also sort by Invitation valid until)
https://test-dhcr.clarin-dariah.eu/users/all
https://test-dhcr.clarin-dariah.eu/users/moderators
https://test-dhcr.clarin-dariah.eu/users/moderated (only mods)

https://test-dhcr.clarin-dariah.eu/cities
https://test-dhcr.clarin-dariah.eu/institutions
https://test-dhcr.clarin-dariah.eu/logentries
https://test-dhcr.clarin-dariah.eu/logentries/errors

unchanged (no need to test, only for info):
https://test-dhcr.clarin-dariah.eu/languages
https://test-dhcr.clarin-dariah.eu/countries

Can you change the label to done, if satisfied?

**Comment by PixlTracer** [comment]
hi @patrickakk 
thank you for fixing!!
I checked the links in test, works fine!!

**Comment by patrickakk** [comment]
Implemented in 2024-12
