### ISSUE TITLE
Info page - Content restructuring

### ISSUE THREAD

**Issue by IvdL22** [acdh-oeaw/dhcr-main#23]
We could restructure the info page https://test-dhcr.clarin-dariah.eu/info in order to simplify the menu and make the content user-friendlier. 

**About** 

**Purpose and Audience**

- [x] I would replace the title with _How to Use DHCR_
- [ ] The content needs slight improvement.

** #19 **

- [ ] If we add contact cards of all the moderators, the section will be very long (just an observation).
- [ ] The text needs improvement: _The DHCR maintains a system of national moderators, who review newly entered courses, help with registration issues and are encouraged to disseminate the DHCR initiative among institutions of their countries. For not moderated countries, please contact the administrators (listed below)._ -> _The course entries in the DH registry are moderated by a group of national moderators whose details you can find below. The role of the national moderators is to provide assistance with any registration issues and review newly submitted courses. In case there is no national moderator available in your country, please contact the administrators_ (add link to the Contact page).

**Contact: Admin & Bug Report**

- [x] I suggested keeping this simple _Contact_ or _Contact Us_. Note that under Purpose and Audience, we have a _Contact Us_ button. We should be consistent everywhere.

**Dissemination and Impact**

- [ ] Some of the text concerning the dissemination material needs improvement. 
- [ ] I suggest we move the selected presentations and publications to a Zotero library and just insert the link here. This way, we make the content user-friendlier and we can also keep adding new publications to the Zotero library.

**Data and API** 

- [x] Title not consistent with Data Export and API (Sitemap)

**CLARIN and DARIAH**

- [ ] The content and the logos on https://test-dhcr.clarin-dariah.eu/info#clarin-dariah can be moved up under the introduction text. Then you can remove the CLARIN  and DARIAH drop-down button.

**Social Media**

- [ ] Change _Social Media_ into _Follow Us_ to make this consistent with the title in the Sitemap menu. You can then remove _Follow the DH Course Registry_ text.

**FAQ**

- [x] We should add a bit more text here: _Please check our Frequently Asked Questions page to find answers to specific questions regarding the use of the platform._
- [ ] We should list the FAQ questions in alphabetical order so that the users can quickly find what they need.

**Credits** 
ok

**Imprint**
- [x] - [ ] Display this only at the bottom of the page, not needed in the menu, in my opinion.

**Release Notes**

- [x] Add text: _If you are curious about the latest technical developments and enhancements, check our release notes on Github._

**Version**

- [x] You could move the Version number to the Release Notes section to simplify the menu.

**Comment by patrickakk** [comment]
@IvdL22:

Thanks for all the suggestions as well as the comments here: https://github.com/acdh-oeaw/dhcr-main/issues/19#issuecomment-1329450891

I've added it to the agenda for our next meeting, so we can find a way how to deal with so many points.

**Comment by patrickakk** [comment]
@PixlTracer  @IvdL22 : Today in the JFX we decided to postpone this issue until jan-23, so we can focus now on releasing the work which is (almost) finished.

**Comment by patrickakk** [comment]
Can and should the contact form be permanently removed?

**Comment by IvdL22** [comment]
@patrickakk Which contact form do you refer to? As agreed, in Contact us, our email addresses should be removed and replaced with the general helpdesk address.

**Comment by patrickakk** [comment]
@IvdL22  The contact form which was there until nov-22 and is now hidden.

**Comment by patrickakk** [comment]
I recommend to talk about this in a meeting.

**Comment by PixlTracer** [comment]
dear Patrick, 
thank you for all the suggestions 
- I am fine with everything but the zotero library; we can discuss this in the meeting.

**Comment by patrickakk** [comment]
@IvdL22  @PixlTracer 
Can you review this?

**I've checked the boxes above for requests which are implemented.**
You can find the result here:
https://dev-dhcr.clarin-dariah.eu/info
and in the menu.

>  The text needs improvement: The DHCR maintains a system of national moderators, who review newly entered courses, help with registration issues and are encouraged to disseminate the DHCR initiative among institutions of their countries. For not moderated countries, please contact the administrators (listed below). -> The course entries in the DH registry are moderated by a group of national moderators whose details you can find below. The role of the national moderators is to provide assistance with any registration issues and review newly submitted courses. In case there is no national moderator available in your country, please contact the administrators (add link to the Contact page).

I couldn't find the text. Maybe it moved here: https://dev-dhcr.clarin-dariah.eu/national-moderators
or here:
https://dev-dhcr.clarin-dariah.eu/info#contact
Which parts should be replaced?

> The content and the logos on https://test-dhcr.clarin-dariah.eu/info#clarin-dariah can be moved up under the introduction text. Then you can remove the CLARIN and DARIAH drop-down button.

I would recommend to keep them there. Moving them to the top will fill the whole screen with text and images and makes all the menu options/accordions invisible.

>  Change Social Media into Follow Us to make this consistent with the title in the Sitemap menu. You can then remove Follow the DH Course Registry text.

The "Social Media" item at the info page is redundant and contains the exact same data as https://dev-dhcr.clarin-dariah.eu/follow#social-media  

- [ ] We could also remove it completely, since there is already "Follow Us" as main menu item. Would that be ok?

The "Follow Us" contains 3 components: Course alert, Social Media and Contributor Mailing list. So changing the text from social media to follow us, would exclude the two other components. Can you specify the preferred change?

> We should list the FAQ questions in alphabetical order so that the users can quickly find what they need.

You can change the order of the questions yourself at: Dashboard / Category Lists / FAQ Questions, then choose a category and move questions up and down.
The current implementation allows you, as administrator, to create every order you want. Even move more important questions to the top?
Would that help?

> Display this(imprint) only at the bottom of the page, not needed in the menu, in my opinion.

I've removed it from the menu. For technical reasons it might be easier to keep it in the accordion menu. If you still want it to disappear there, I should spend some more time on it and move it to a separate page.

Please let me know what you think of all this and if additional changes are needed.

**Comment by patrickakk** [comment]
Btw the menu and accordeons at the info page are also inconsistent: "National Moderators" appears in the menu, but at the Info page we've merged it under "Contact Us". What should be do about that?

**Comment by PixlTracer** [comment]
simply keep 'contact us' ---> the user can find out more then via the National Moderators page, which is linked there

**Comment by patrickakk** [comment]
@PixlTracer Done. The entry "National Moderators" has been removed from the menu.

@PixlTracer @IvdL22 

Could you answer the questions above? See https://github.com/acdh-oeaw/dhcr-main/issues/23#issuecomment-1618262560

Can you review this issue, maybe that a look at (your own) suggestions above, and specify if additional changes are needed? Or can the label be changed to done?

**Comment by PixlTracer** [comment]
I've checked everything and to me it looks fine; if Iulianna agrees, we can set the label to done

**Comment by IvdL22** [comment]
Fine with me as all @PixlTracer and @patrickakk !Thank you for the changes, Patrick.

**Comment by patrickakk** [comment]
Implemented in 2023-08.
