### ISSUE TITLE
Number of courses: API vs. DHCR Statistics

### ISSUE THREAD

**Issue by PixlTracer** [acdh-oeaw/dhcr-main#63]
The number of course counts in the [DHCR course statistics dashboard](https://dhcr.clarin-dariah.eu/statistics/course-statistics) differs from the number of courses retrieved [via the API](https://dhcr.clarin-dariah.eu/api/v2/courses/count?recent) ([API overview page](https://dhcr.clarin-dariah.eu/api/v2/) - count results)

**Comment by patrickakk** [comment]
Thanks for creating the issue.

In our meeting on 2023-03-08 we agreed that this will have low priority.

Note: The current numbers are 184 and 186, so the difference is 2 courses.
This might have to do with the way in which the course expiration time is calculated. This is done differently in different parts of the application.

**Comment by patrickakk** [comment]
@PixlTracer  @IvdL22 

Both API's (v1 and v2) were using an older version of DhcrCore. The older version contained a bug. This caused that unapproved courses were shown in the public registry. This was solved on 2022-10-31 with commit b0636e798e72536eb86cc071313a4bc7d6e77dd9 in DhcrCore

Since yesterday both API's are also using the new version and now the counts in the API are also based on the correct criteria.

https://test-dhcr.clarin-dariah.eu/statistics/course-statistics
https://test-dhcr.clarin-dariah.eu/api/v1/courses/count?recent
https://test-dhcr.clarin-dariah.eu/api/v2/courses/count?recent

@PixlTracer Can you check if you still experience differences? When not, please change the label to done and write a short line.

**Comment by patrickakk** [comment]
@IvdL22  @PixlTracer Can you review this?   

 Please change the label to Done when you're satisfied.

**Comment by PixlTracer** [comment]
perfect, thank you!

**Comment by patrickakk** [comment]
Implemented in 2023-02
