### ISSUE TITLE
Add the logos on the DHCR landing page

### ISSUE THREAD

**Issue by IvdL22** [acdh-oeaw/dhcr-main#87]
Please add the CLARIN and DARIAH logos on the [DARIAH landing page](https://dhcr.clarin-dariah.eu/) to make it clear that it is a DARIAH-CLARIAH effort.

Edit PA 2023-11-16: I suppose that the DHCR landing page is meant, instead of DARIAH landing page ;)

**Comment by patrickakk** [comment]
@IvdL22 

- What size should the logos be? The same height as the DHCR logo, or for example 75% of the height? (The width could be adjusted based on image proportions)

- Can you specify the url (or attach here) the up-to-date versions of both logo's?
(For example the CLARIN logo, found on https://dhcr.clarin-dariah.eu/info#clarin-dariah is different from the one on https://www.clarin.eu/)

- Which logo should be shown first?

**Comment by patrickakk** [comment]
@IvdL22 cc @PixlTracer 
Thanks for your email. Below I'll quote the relevant, public available, links:

> The style guide can be found [here](https://www.clarin.eu/content/clarin-eric-style-guide).

> A handy ‘cheat sheet’ summarising the basic guidelines is available [here](https://www.clarin.eu/sites/default/files/CheatSheet_CLARIN-Style-Guide_September2023.pdf).

The cheatsheet contains:

> An overview of the CLARIN logos [here]

Which points to: https://www.clarin.eu/content/clarin-community-logos

This link contains a total of 9 logos.

Can you specify which one of those 9 logos you meant? ;)

And as well answer the other questions from the comment above?


>     What size should the logos be? The same height as the DHCR logo, or for example 75% of the height? (The width could be adjusted based on image proportions)
> 
>     Can you specify the url the up-to-date versions of both logo's?
> 
>     Which logo should be shown first?
> 

So that it can be implemented in the way it's needed.

**Comment by IvdL22** [comment]
Hi @patrickakk You can use the first logo from the CLARIN page: https://www.clarin.eu/content/clarin-community-logos. 

As for the DARIAH logo, I asked some colleagues at DARIAH but no reply yet. In any case, their logo has not changed and you could use the same that we have on the DHCR website.

Size: they should be smaller than the DHCR logo, I think.

Order: alphabetical order: CLARIN & DARIAH.

**Comment by patrickakk** [comment]
@IvdL22 @PixlTracer 

The feature you've requested is ready.

You can find the new logo on the main page in the test instance.

Can you change the label to Done if satisfied?

**Comment by PixlTracer** [comment]
thank you!

**Comment by patrickakk** [comment]
Implemented in 2023-12

**Comment by patrickakk** [comment]
@IvdL22 @PixlTracer 

Nice to read that the change is appreciated.

Another thought crossed my mind and based on that I was able to implement two additions.

Considerations:
In the "before" situation the old logo was linked to the main/home page. This was especially useful when applying filters or viewing course details on the map and then returning to the beginning.

The new header logo was not clickable and there was no option to go back to "home". Since the new header logo consists of one image which contains the three logo's and is/should also be scalable/responsive, it's difficult to link this to three different url's.

The two additions are:
1. Added a "Home" button before the filter options.
2. Linked the complete header logo  to Info -> CLARIN and DARIAH, where users can find an explanation and links to both organizations.

You can find the additions in the test instance.

Can you change the label to Done if satisfied?

**Comment by PixlTracer** [comment]
very nice work and straight forward thinking, 
thank you for this, @patrickakk

**Comment by patrickakk** [comment]
Implemented in 2023-12
