### ISSUE TITLE
keyword option for DHCR

### ISSUE THREAD

**Issue by ehanscam** [acdh-oeaw/dhcr-main#90]
Hello, 

It would be great to have the option to tag courses with keywords, so we can search by tag and note the national infrastructure involved, for instance.

**Comment by patrickakk** [comment]
@IvdL22 @PixlTracer @vronk See the request above as info.

It's related to this issue: https://github.com/acdh-oeaw/dhcr-main/issues/88

**Comment by patrickakk** [comment]
Added SpecsMissing label, see other issue.

Added to November milestone so it stays in focus and we can discuss this in one of the following meetings.
Then we can take a decision? And reschedule the issue?

**Comment by PixlTracer** [comment]
proposal:
when entering (writing) something in the search bar --> hit enter 
--> a checkbox appears "also search in course description"
when ticking this box, the system crawls the metadata content of the course description field

**Comment by patrickakk** [comment]
@PixlTracer 
Can we see this as part of the bigger issue, here: https://github.com/acdh-oeaw/dhcr-main/issues/88

A few remarks:
- It's not that difficult to implement a search in the description.
- This issue is about adding a tag/keyword to a course, not searching in the description?
- The current behavior of the search bar is to respond to every character which is entered (typeahead) without pressing enter. Do you suggest to change this?
- The suggested checkbox could also be shown by default?
- What when the search in the description is implemented and then we decide to add tags?

Can we please continue (or start) the discussion in the other issue?

**Comment by vronk** [comment]
This will be tackled in course of revamping the search, cf. #88
