### ISSUE TITLE
Cron jobs do not work

### ISSUE THREAD

**Issue by PixlTracer** [acdh-oeaw/dhcr-main#93]
when I search for something in the searchbar at https://dhcr.clarin-dariah.eu/, nothing is happening, even if I press enter; 

inspection shows that a file/script is not available: Error 404, unable to reach server 
(https://dhcr.clarin-dariah.eu/search_list.json)

**Comment by patrickakk** [comment]
@PixlTracer Thank you for reporting this. Indeed the required file is not generated. For now I've done this manually, so the search bar does work again ;)

The bug is not fixed. I'll keep you updated when there is news.

**Comment by patrickakk** [comment]
For some reason I can't reproduce this problem :-P
After redeploying the container (with the same code) it works fine. Both in test and production.

Although I noticed that some jobs which should update items didn't work. (generate search list, generate sitemap and send course reminders).

I did run the course reminders manually. The next automatic run should be at the 19th.

I've implemented a fix in production (since the cron jobs only work in production).

Within 1 hours from now you can check if it works, by login -> Category Lists -> Log Entries. That should show an entry "GenSearchList | Generated list" every hour. Than we can be sure the search bar is not only working, but also always up-to-date ;)

Feel free to check the issue within 1 hours from now and change to Done if it works ;)

**Comment by patrickakk** [comment]
No need to check...yet ;)  Now it fails because of another error (intl extension not enabled in container for cron job).

So the current status is: the search bar does work, but doesn't get updated. (As well generate sitemap and course reminders should be checked).

**Comment by patrickakk** [comment]
Status:
broken cron jobs since migration to Heroku 22

**Comment by patrickakk** [comment]
Related commits:
9861d76165a3d27ce9af73193bb25faf15a796a3
c9634b7586c3c9929bf614f6db9959f0f77670c9
d6f6aecdfb05392574fe8a43c620902994bcdba4
6cc564265a6554235f1d712086b2b8ac1cca23af
944469654ff1a6afafc0764be6e202001d01fdbf
55a3b32a69fe7a2b2f0cca28b36283dc4c0142ba

**Comment by patrickakk** [comment]
@PixlTracer @IvdL22 

The searchbar was already fixed. Now all the cron jobs also work as they are supported to. You can check that in **production** only: Dashboard / Category Lists / Log Entries.

- Generating search list runs every hour. Since the recent problems at ACDH which are sometimes also affecting the searchbar, today I've changed this to every 30 mins. So in case of some strange container restart at ACDH it should recover within 30 mins. If problems still exists, we could also make this more often, for example every 5 mins.
- Generating sitemap runs every day
- Course reminders runs every 4th and 19th of the month.

Logs are available as specified above.

Can you change the label to Done if satisfied?

**Comment by PixlTracer** [comment]
great job Patrick, thank you

**Comment by patrickakk** [comment]
This issue can be closed.

For implementation there is no version number, since this change has been made in production, on: 2024-01-30.

Commits here:
https://github.com/acdh-oeaw/dhcr-main/issues/93#issuecomment-1917668948
