### ISSUE TITLE
Change the colour of the hyperlinks embedded in the text

### ISSUE THREAD

**Issue by IvdL22** [acdh-oeaw/dhcr-main#94]
To improve the accessibility of the content for people with special needs, please change the colour of the text containing hyperlinks, e.g use lighter blue, similar to the hyperlinks on the CLARIN website. I have already discussed this with Patrick.

**Comment by patrickakk** [comment]
![image](https://github.com/acdh-oeaw/dhcr-main/assets/97846194/05e19842-c09c-4937-931f-c5a292605d53)

**Comment by patrickakk** [comment]
@IvdL22 
cc @PixlTracer 

I've changed the color of all occurrences of hyperlinks. The color has been changed to a lighter blue color, as used on the CLARIN website for the links under "Upcoming events". See the above image for the exact part from which I used the color.

I'm not sure if this is an improvement? It does change the complete look & feel of the application at bit?
Does this solve the problem or do you prefer to change it to another color?

Feel free to suggest other options, so that we can both solve the problem you described above and have a color which fits the best to the style of other items in the application.

The changes are available in the test instance.

Can you change the label to Done if satisfied?

**Comment by IvdL22** [comment]
@patrickakk I checked and the hyperlinks are much more visible now. Much appreciated! Also, the CLARIN and DARIAH logos look nice.

**Comment by patrickakk** [comment]
Implemented in 2023-12
